server:
  servlet:
    context-path: /oauth-server
  port: 8082
spring:
  application:
    name: authorization-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

