server:
  port: 8888

spring:
  application:
    name: admin-service
  security:
    user:
      name: admin
      password: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka